### ISSUE TITLE
Link to working document in the guidelines

### ISSUE THREAD

**Issue by FelixDGG** [KhronosGroup/3DC-Asset-Creation#2]
In section sec03_Geometry under "Polygon Count" the word "base asset" leads to the working version of the guidelines:
https://docs.google.com/document/d/1UfUJpDPDOk35kGxZ_vuJhPPQxXt_gtSBDt99ogEDhFQ/edit#heading=h.q4349om3p379

I assume this is not intentional and the link should be removed.

**Comment by vanlicht** [comment]
Issue resolved
