### ISSUE TITLE
Sections contain broken links to summary

### ISSUE THREAD

**Issue by mlimper** [KhronosGroup/3DC-Asset-Creation#3]
Example:

Link at the bottom here `https://github.com/KhronosGroup/3DC-Asset-Creation/blob/main/asset-creation-guidelines/full-version/sec99_PublishingTargets/PublishingTargets.md`

**Comment by vanlicht** [comment]
Could you check if the issue is resolved?

**Comment by mlimper** [comment]
Hey, thanks - I tested and it works for all sections now, except for "glTF and USDZ":
https://github.com/KhronosGroup/3DC-Asset-Creation/blob/main/asset-creation-guidelines/full-version/sec100_GltfAndUsdz/GltfAndUsdz.md

**Comment by mlimper** [comment]
OK, fixed now (I am member of the Khronos Group on GitHub, so I was able to commit myself without PR: https://github.com/KhronosGroup/3DC-Asset-Creation/commit/465cec6fc7fdc0d4007d9be9d154273f30fcd5c1)
